# ==============================================================================
# Ansible Inventory File
# Project: Automated Web Deployment on AWS (DevOps IA Project)
# ==============================================================================
# Maps target AWS EC2 instances into environment groups (Dev & Prod).
# Ansible uses these host definitions to connect and run playbooks.
# ==============================================================================

# --- Development Environment Host ---
[dev]
dev_server ansible_host=16.176.204.1

# --- Production Environment Host ---
[prod]
prod_server ansible_host=3.25.242.241

# ==============================================================================
# Global Variables applied to ALL managed hosts
# ==============================================================================
[all:vars]
# Default SSH user for Amazon Linux 2023
ansible_user=ec2-user

# Path to the private SSH key generated in Sprint 0
ansible_ssh_private_key_file=~/.ssh/devops_aws_key

# Prevents SSH from halting automation to prompt for host key authenticity confirmation
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
